name: Deploy Angular App with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build:prod
      - name: rename index for routing
        run: mv dist/proyecto-ieee-page/index.html dist/proyecto-ieee-page/404.html
        
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/proyecto-ieee-page
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

